language: android

sudo : false

jdk: openjdk8

android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
  licenses:
    - ".+"

branches:
  only:
    - master

script:
  - source ci/style-check.sh
  - ./gradlew assemble bundle check

notifications:
  email: false

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.gradle"

before_install:
 - yes | sdkmanager "ndk-bundle"